### ISSUE TITLE
crayfish plugin doesnt work in qgis 3.20

### ISSUE THREAD

**Issue by Maiyourathaan** [qgis/OLD-QGIS-Website-see-QGIS-Website-for-current-one#934]
I have installed QGIS 3.20 in my computer and wanted to use crayfish plugin for Mesh analysis. When I install the plugin it shows the following error and the plugin does not appearing in the toolbox window.

Couldn't load plugin 'crayfish' due to an error when calling its classFactory() method 

AttributeError: module 'time' has no attribute 'clock' 
Traceback (most recent call last):
  File "C:\AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\crayfish\gui\plot_widget.py", line 38, in 
    import pyqtgraph
  File "C:\PROGRA~1/QGIS32~1.2/apps/qgis/./python\qgis\utils.py", line 799, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pyqtgraph'

**Comment by DelazJ** [comment]
@Maiyourathaan This repository is to manage QGIS website. The issue you are reporting is a Crayfish plugin issue so should be reported in the plugin issue tracker.
